version: '3'
services:
  api:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - app
    # ...

  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity

  dev:
    image: alpine:edge
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - mongodb
      - cache
      
  mongodb:
    image: mongodb/mongodb-community-server
    restart: unless-stopped
    networks:
      - nwk1
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  cache:
    # array access with '.' is broken in v1.19.1
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.18.1
    restart: unless-stopped
    networks:
      - nwk1
    ports:
      - 6379:6379

volumes:
  mongo_db:

networks:
  nwk1:
